
import * as d from './proxies';

export const DIRECTIVES = [
d.BalAccordion,
  d.BalButton,
  d.BalCard,
  d.BalCardActions,
  d.BalCardButton,
  d.BalCardContent,
  d.BalCardHeading,
  d.BalCardStep,
  d.BalCardSteps,
  d.BalCardSubtitle,
  d.BalCardTitle,
  d.BalCheckbox,
  d.BalData,
  d.BalDataItem,
  d.BalDataLabel,
  d.BalDataValue,
  d.BalDropdown,
  d.BalField,
  d.BalFileUpload,
  d.BalHint,
  d.BalHintText,
  d.BalHintTitle,
  d.BalIcon,
  d.BalInput,
  d.BalList,
  d.BalListItem,
  d.BalListItemContent,
  d.BalListItemIcon,
  d.BalListItemSubtitle,
  d.BalListItemTitle,
  d.BalSelect,
  d.BalSelectOption,
  d.BalSpinner,
  d.BalText
];
