name: Continous

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Clean install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Git Status
        run: git status

      - name: Builded libaries are pushed
        run: git diff-index --quiet HEAD --

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
        uses: cypress-io/github-action@v2

